export const SEARCH_CONFIG = {
  pet_parents:     { placeholder: "full_name",     column: "full_name"      },
  pets:            { placeholder: "name",           column: "name"          },
  medical_records: { placeholder: "title",          column: "title"         },
  vaccinations:    { placeholder: "Vaccine_Name",   column: "vaccine_name"  },
addresses:       { placeholder: "city or pincode", columns: ["city", "pincode"] },
  doctors:         { placeholder: "name",           column: "name"          },
  clinics:         { placeholder: "name",           column: "name"          },
  service_providers: { placeholder: "name",         column: "name"          },
  services:        { placeholder: "title",          column: "title"         },
  products:        { placeholder: "name",           column: "name"          },
  categories:      { placeholder: "name",           column: "name"          },
  brands:          { placeholder: "name",           column: "name"          },
  sellers:         { placeholder: "business_name",  column: "business_name" },
  warehouses:      { placeholder: "name",           column: "name"          },
  orders:          { placeholder: "order_number",   column: "order_number"  },
  order_items:     { placeholder: "product_name",   column: "product_name"  },
  gps_locations:   { placeholder: "city",           column: "city"          },
  notifications:   { placeholder: "title",          column: "title"         },
  vendor_membership_plans:{ placeholder: "name",          column: "name"           },
  support_tickets: { placeholder: "subject",        column: "subject"       },
  geocoding_cache: { placeholder: "query",          column: "query"         },
  audit_logs:      { placeholder: "action",         column: "action"        },
  sales_executives:{ placeholder: "name",          column: "name"           },
  pincode_coverage:{ placeholder: "pincode",       column: "pincode"        },
  executive_tasks: { placeholder: "title",          column: "title"         },
  executive_alerts:{ placeholder: "title",         column: "title"          },
};
